CREATE DATABASE trabalho;
USE trabalho;

CREATE TABLE usuarios (
  id INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45) NOT NULL,
    SENHA VARCHAR(12) NOT NULL,
  EMAIL VARCHAR(110) NOT NULL,
  TELEFONE VARCHAR(15) NOT NULL,
  SEXO VARCHAR(15) NOT NULL,
  DATA_NASCT DATE NOT NULL,
  PRIMARY KEY (id))engine=innodb;
select * from usuarios;